apiVersion: v1
kind: ConfigMap
metadata:
  name: swagger-spec
  namespace: demo
data:
  openapi.yaml: |
    openapi: "3.0.0"
    info:
      title: Demo API
      version: "1.0"
    paths:
      /hello:
        get:
          responses:
            '200':
              description: ok
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-ui
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
        - name: swagger
          image: swaggerapi/swagger-ui:latest
          ports:
            - containerPort: 8080
          env:
            - name: SWAGGER_JSON
              value: /etc/swagger/openapi.yaml
          volumeMounts:
            - name: swagger
              mountPath: /etc/swagger
      volumes:
        - name: swagger
          configMap:
            name: swagger-spec
---
apiVersion: v1
kind: Service
metadata:
  name: swagger
  namespace: demo
spec:
  selector:
    app: swagger-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
